##  1. 解决异步的方法
- callback（回调函数）
- generator + Co库
- promise
- async + await

## 2. promise基本介绍

### 2.1 回调带来的问题 

- 嵌套层次很深，难以维护。（回调地狱） 
- 无法正常的使用return和throw 
- 无法正常检索堆栈信息 
- 多个回调之间难以建立联系 

### 2.2 含义 

Promise简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上来说，Promise是一个对象，从它可以获取异步操作的消息。Promise提供统一的API，各种异步操作都可以用同样的方法进行处理。

### 2.3 两个特点

1. 对象的状态不受外界影响。Promise对象代表一个异步操作，有3种状态。只有异步操作的结果可以决定当前是哪一种状态，任何其它操作都无法改变这个状态。这也是“Promise”这个名字的由来，表示其它手段无法改变。

   + pending [待定]　初始状态 
   + fulfilled [实现]　操作成功 
   + rejected [被否决]　操作失败 

2. 一旦状态改变就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变只有两种可能。只要这两种情况发生，状态就凝固了，不会再变，而是一直保持这个结果，这时就称为Resolved（已定型）。就算改变已经发生，再对Promise对象添加回调函数，也会立即得到这个结果。当Promise的状态发生改变，就会触发.then()里的响应函数处理后续步骤 。

   + 从Pending变为Fullfilled
   + 从Pending变为Rejected

   > 为了方便，后面的 Resolved 统一指 Fulfilled 状态，不包含 Rejected 状态 。

### 2.4 缺点

1. 无法取消Promise，一旦新建它就会立即执行，无法中途取消。
2. 如果不设置回调函数，Promise内部抛出的错误不会反应到外部。
3. 当处于Pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）

### 2.5 基本结构

```js
var promise = new Promise(function(resolve, reject) {
    // ...
    if (/* 异步操作成功 */) {
        resolve(value)
    }else{
		reject(error)
    }
})

promise.then(function(value} { 
	// success 
}, function (error) { 
	// failure 
}); 
```

- Promise构造函数接收两个函数作为参数：resolve和reject。
  - resolve：将Promise对象状态从“未完成”变为“成功”（即从Pending变为Resolved)，在异步操作成功时调用
  - reject : 将Promise对象状态从“未完成”变为“失败”（即从Pending变为Rejected)，在异步操作失败时调用，并将异步操作报出的错误作为参数传递出去。
- Promise实例生成以后，可以用then方法分别指定Resolved状态和Rejected状态的回调函数。then方法可以接受两个回调函数作为参数。这两个函数都接受Promise对象传出的值作为参数。
  - 第一个回调函数时Promise对象状态变为Resolved时调用
  - 第二个回调函数是可选的，不一定要提供。是Promise对象状态变为Rejected时调用

### 2.6 执行顺序

Promise 新建后就会立即执行 。

.then方法指定的回调函数会在当前脚本所有同步任务执行完成后才会执行。

调用 resolve 或 reject 并不会终结 Promise 的参数函数的执行。

```js
let promise = new Promise(function(resolve, reject) { 
    console.log ('Promise'); 
    resolve(); 
    console.log(2); 
}); 
promise.then(function() {
    console.log('Resolved')
})
console.log('Hi!'); 

// Promise
// 2
// Hi!
// Resolved
```

一般来说，调用 resolve 或 reject 以后， Promise 的使命就完成了，后继操作应该放到then 方法里面，而不应该直接写在 resolve 或 reject 的后面。所以，最好在它们前面加上return 吾句，这样就不会产生意外 。

### 2.7 实现

```js
function MyPromsie(fn) {
    //默认状态为pending
    this.status = 'pending';
    //存放promise最终的值
    this.value = undefined;
    //存放所有成功的回调函数
    this.onResovledCallbacks = [];
    //存放所有失败的回调函数
    this.onRejectedCallbacks = [];
    let that = this;
    //调用这个方法可以把promise变成成功的状态
    function resovle(value) {
        if (value instanceof Promise) {
            return value.then(resovle, reject);
        }
        if (that.status == 'pending') {
            that.status = 'fulfilled';
            that.value = value;
            that.onResovledCallbacks.forEach(item => item(that.value));
        }
    }
    //调用这个方法可以把promise变成失败的状态
    function reject(reason) {
        if (that.status == 'pending') {
            that.status = 'rejected';
            that.value = reason;
            that.onRejectedCallbacks.forEach(item => item(that.value));
        }

    }
    try {
        fn(resovle, reject);
    } catch (e) {
        reject(e)
    }
}


```



## 3.  Promise.prototype.then() 

### 3.1 基本介绍

Promise 实例具有 then 方法，即 then 方法是定义在原型对象 Promise.prototype 上的 。它的作用是为Promise 实例添加状态改变时的回调函数。

- 第一个回调函数时Promise对象状态变为Resolved时调用
- 第二个回调函数是可选的，不一定要提供。是Promise对象状态变为Rejected时调用

### 3.2 链式调用

then 方法返回的是一个新的 Promise 实例 。因此可以采用链式写法，即 then 方法后面再调用另一个 then 方法。

```js
getJSON ("/posts.json").then (function (json) { 
	return json.post; 
}).then (function (post) { 
	// ...
});
```

### 3.3 实现

```js
MyPromise.prototype.then = function (onFulfilled, onRejected) {
    let that = this;
    return new MyPromise((resovle, reject) => {
        if (typeof onFulfilled !== 'function') {
            //设置onFulfilled为函数，返回值和传入的值一致
            onFulfilled = ele => ele;
        }
        if (typeof onRejected !== 'function') {
            onRejected = err => {
                throw new Error(err);
            };
        }

        if (that.status == 'fulfilled') {
            let x = onFulfilled(that.value);
            resovle(x);
        }

        if (that.status == 'rejected') {
            onRejected(that.value);
        }

        if (that.status == 'pending') {
            that.onResovledCallbacks.push(function () {
                onFulfilled(that.value);
            });
            that.onRejectedCallbacks.push(function () {
               onRejected(that.value);
            });
        }
    })
}
```



## 4. Promise.prototype.catch() 

### 4.1 基本介绍

Promise . prototype . catch 方法是 . then(null, rejection ）的别名，用于指定发生错误时的回调函数。包括捕获reject函数和运行中抛出的错误。

如果 Promise 状态己经变成 Resolved ，再抛出错误是无效的。

```js
var promise = new Promise(function (resolve, reject) { 
    resolve ('ok'); 
    throw new Error ('test'); 
});
promise 
	.then (function(value) { console.log(value) }) 
	.catch (function(error) { console.log(error) }); 
// ok 
```

Promise 对象的错误具有“冒泡”性质 ， 会一直 向后传递， 直到被捕获为止。 也就是说，错误总是会被下一个 catch 语句捕获。

```js
getJSON ('/post/1.json').then(function(post) { 
	return getJSON(post.commentURL) ; 
}).then (function(comments) { 
	// some code 
}).catch (function(error) { 
	// 处理前面 3 个 Promise 产生的错误
}); 

上面的代码中， 一共有 3 个 Promise 对象： 一个由 getJSON 产生，两个由 then 产生。其中任何一个抛出的错误都会被最后一个 catch 捕获。
```

catch 方法返回的还是一个 Promise 对象，因此后面还可以接着调用 then方法。如果没有报错，则会跳过 catch 方法，执行后面.then的代码。

```js
Promise.resolve() 
	.catch(function(error) { 
		console.log ('oh no', error); 
	}) 
	.then(function() { 
		console.log ('carry on'); 
	}); 
// carry on 
```

catch 方法中还能再抛出错误。抛出的错误会在后面的catch中被捕获。



### 4.2 推荐写法

一般说来，不要在 then 方法中定义 Rejected 状态的回调函数（即 then 的第二个参数)，而应总是使用 catch 方法。

```js
// bad 
promise 
	.then (function (data) { 
		// success 
	}, function (err) { 
		// error 
	}); 

// good 
promise 
	.then(function(data) { 
 		// success 
	}) 
	.catch(function(err) { 
		// error 
	});	 
```

## 5. Promise.all() 

### 5.1 基本介绍

Promise.all 方法用于将多个 Promise 实例包装成一个新的 Promise 实例。

```js
var p = Promise.all([pl, p2, p3]) ;
```

Promise all 方法接受一个数组作为参数 ， p1,  p2, p3 都是 Promise对象的实例：如果不是 ， 就会先调用下面讲到的 Promise.resolve 方法， 将参数转为 Promise实例 ，再进一步处理（ Promise . al l 方法的参数不一定是数组 ， 但是必须具有 Iterator 接口 ，且返回的每个成员都是 Promise实例）。

### 5.2 返回值

p 的状态由Promise 实例参数（假定是p1、p2、p3） ， 返回值分成两种情况：

1. 只有p1、p2、p3的状态都变成 Fulfilled , p 的状态才会变成 Fulfilled ，此时 p1、p2、p3 的返回值组成一个数组，传递给 p 的回调函数。
2. 只要 p1、p2、p3中有一个被 Rejected , p 的状态就变成 Rejected ， 此时第一个被 Rejected的实例的返回值会传递给 p 的回调函数。也就是失败的时候返回最先被reject失败状态的值。

```js
const pl = new Promise((resolve, reject) => {
    resolve('hello');
})
.then(result => result)
.catch(e => e);

const p2 = new Promise((resolve, reject) => {
    throw new Error('报错了');
})
.then(result => result)
.catch(e => e);

Promise.all([pl, p2])
    .then(result => console.log(result))
    .catch(e => console.log(e));
// ['hello', Error ：报错了] 
```

上面的代码中， p1 会 resolved, p2 首先会rejected ，但是 p2 有自己的 catch 方法，该方法返回的是一个新的 Promise 实例， p2 实际上指向的是这个实例。该实例执行完 catch方法后也会变成 resolved ，导致 Promise. all() 方法参数里面的两个实例都会 resolved,因此会调用 then 方法指定的回调函数，而不会调用 catch 方法指定 的回调函数。因此如果 p2 没有自己的 catch 方法，p2的结果就会变成Rejected，就会调用 Promise.all() 的 catch 方法，这个时候输出的是“Error ：报错了”。

### 5.3 返回顺序

需要特别注意的是，Promise.all获得的成功结果的数组里面的数据顺序和Promise.all接收到的数组顺序是**一致**的，即p1的结果在前，即便p1的结果获取的比p2要晚。这带来了一个绝大的好处：在前端开发请求数据的过程中，偶尔会遇到发送多个请求并根据请求顺序获取和使用数据的场景，使用Promise.all毫无疑问可以解决这个问题。 

### 5.4 实现

- 传入的是一个promise对象的数组 
- 返回的是一个Promise对象 
- 由于promise只能resolve一次，应该在所有的promise对象都执行的时候才执行resolve，当碰到一个promise执行失败的时候就直接reject 

```js
Promise.myall = promises => {
    let result = [], len = promises.length;
    return new Promise((resolve,reject) => {
        promises.forEach(promise => {
            promise.then(res => {
                result.push(res);
                if(result.length == len){
                    resolve(result);
                } },res => {
                reject(res);
            })
        });
    });
}
```



## 6. Promise.race()

### 6.1 基本介绍

Promise.race 方法同样是将多个 Promise 实例包装成一个新的 Promise 实例。

```js
var p = Promise.race([pl, p2, p3]) ;
```

上面的代码中，只要 pL p2, p3 中有一个实例率先改变状态， p 的状态就跟着改变。那个率先改变的 Promise 实例的返回值就传递给 p 的回调函数。

Promise. race 方法的参数与 Promise.all 方法一样，如果不是 Promise 实例，就会先调用下面讲到的 Promise.resolve 方法，将参数转为 Promise 实例 ，再进一步处理。

```js
const p = Promise.race([
     fetch('/resource-that-may-take-a-while'),
     new Promise(function (resolve, reject) {
         setTimeout(() => reject(new Error(' request timeout ')), 5000)
     })
 ]);
p.then(response => console.log(response));
p.catch(error => console.log(error));
```

上面的代码中，如果 5 秒之内 fetch 方法无法返回结果，变量 p 的状态就会变为 Rejected, 从而触发 catch 方法指定的回调函数。

### 6.2 实现

- 传入的参数是一个promise对象的一个数组
- 返回的是一个Promise对象，所以需要创建一个新的promise。
- 根据promise 只能 resolve 一次的限制，每个迭代值都会创造另一个promise，先resolve的也就会先被主 promise resolve 返回结果。返回晚的自然被废弃不用 

```js
Promise.myrace = function(promises) {
    return new Promise((resolve, reject)=>{
        promises.forEach(promise => {
            promise.then(resolve, reject)
        });
    })
}
```



## 7. Promise.resolve() 

将现有对象转为 Promise 对象。

```js
Promise.resolve ('foo') 
// 等价于
new Promise(resolve =>resolve ('foo')) 
```

Promise.resolve 方法的参数分成以下 4 种情况。

1. 参数是一个 Promise 实例

   不做任何修改，原封不动地返回这个实例。

2. 参数是一个 thenable 实例

   thenable 对象指的是具有 then 方法的对象，比如下面这个对象。

   ```js
   let thenable = { 
       then : function(resolve, reject) { 
       	resolve(42); 
       }
   }
   ```

   Promise .resolve 方法会将这个对象转为 Promise 对象，然后立即执行 thenable 对象的 then 方法。

   ```js
   let pl= Promise.resolve(thenable); 
   pl.then(function(value) { 
   	console.log (value); 	// 42 
   }); 
   ```

3. 参数不是具有 then 方法的对象或根本不是对象

   那么 Promise.resolve方法返回 一个新的 Promise 对象，状态为 Resolved 。

   ```js
   var p = Promise.resolve ('Hello'); 
   p.then(function (s) { 
   	console.log(s) 
   }); 
   ```

4. 不带有任何参数

   Promise.resolve 方法允许在调用时不带有参数， 而直接返回 一个 Resolved 状态的Promise 对象 。

   所以，如果希望得到一个 Promise 对象 ， 比较方便的方法就是直接调用 Promise.resolve方法。

   ```js
   var p = Promise.resolve() ; 
   p.then (function () { 
       // ...
   }
   ```



## 8. Promise.reject() 

Promise.reject(reason）方法也会返回一个新的 Promise 实例，状态为 Rejected 。

```js
var p = Promise.reject('出错了');
// 等同于
var p =new Promise((resolve, reject) =>reject('出错了'))

p.then(null, function (s) { 
	console.log(s) 
}); 
```

Promise.reject() 方法的参数会原封不动地作为 reject 的理由变成后续方法的参数。 这一点与 Promise.resolve 方法不一致。

```js
const thenable = { 
	then (resolve, reject) { 
		reject('出错了');
    }
}
Promise.reject(thenable) 
	.catch(e => { 
		console.log(e === thenable) 
	}) 
// true 
```

## 9. done()

### 9.1 基本介绍

无论 Promise 对象的回调链以 then 方法还是 catch 方法结尾，只要最后一个方法抛出错误， 都有可能无法捕捉到（因为 Promise 内部的错误不会冒泡到全局） 。为此，我们可以提供一个 done 方法，它总是处于回调链的尾端，保证抛出任何可能出现的错误。

```js
asyncFunc() 
    .then(fl) 
    .catch(rl) 
    .then(f2) 
    .done(); 
```

### 9.2 实现

它的实现代码相当简单。

```js
Promise.prototype.done = function (onFulfilled, onRejected) { 
	this.then(onFulfilled, onRejected) 
		.catch(function (reason) { 
		// 抛出一个全局错误
		setTimeout(() => { throw reason }, 0); 
    }
});
```

由上可见， done 方法可以像 then 方法那样使用，提供 Fu lfilled 和 R句 ected 状态的回调函数，也可以不提供任何参数。但不管怎样， done 方法都会捕捉到任何可能出现的错误，并向全局抛出。

## 10. finally()

### 10.1 基本介绍

finally 方法用于指定不管 Promise 对象最后状态如何都会执行的操作。它与 done 方法的最大区别在于，它接受一个普通的回调函数作为参数，该函数不管怎样都必须执行 。

下面是一个例子 ，服务器使用 Promise 处理请求，然后使用 finally 方法关掉服务器 。

```js
server.listen(0) 
	.then(function () { 
		// run test 
	}) 
	.finally(server.stop) ;
```

### 10.2 实现

```js
Promise.prototype.finally = function (callback) { 
	let P = this.constructor; 
	return this.then( 
		value => p.resolve (callback()).then (() => value), 
		reason=> P.resolve(callback()).then(() => { throw reason }) 
    }
}
```

上面的代码中 ， 不管前面的 Promise 是 fulfilled 还是 rejected ，都会执行回调函数callback 。



## 11. Promise.try() 

实际开发中经常遇到一种情况： 不知道或者不想区分函数 f 是同步函数还是异步操作，但是想用 P romise 来处理它 。 因为这样就可以不管 f 是否包含异步操作，都用 then 方法指定下一步流程 ，用 catch 方法处理 f 抛出的错误 。一般的写法如下:

```js
Promise.resolve().then(f) 
```

上面的写法有一个缺点 ： 如果 f 是同步函数，那么它会在本轮事件循环的末尾执行。

```js
const f = () => console.log ('now'); 
Promise.resolve().then(f); 
console.log('next'); 

// next 
// now 
```

那么有没有一种方法，让同步函数同步执行，让异步函数异步执行，并且让它们具有统一的 API 呢？回答是有的，并且还有两种写法 。

-  第一种写法是使用 async 函数。

  ```js
  const f = () =>console.log('now');
  (async () => f()) () ; 
  console.log ('next');
  // now
  // next
  ```

- 第二种写法是使用 new Promise()

  ```js
  const f = () => console.log('now');
  (
      () => new Promise(
          resolve => resolve(f())
      ) 
  )()
  console.log('next');
  
  // now
  // next
  ```

  上面的代码也是使用立即执行的 匿名函数来执行 new Promise()的 。这种情况下，同步函数也是同步执行的。



鉴于这是一个很常见的需求，所以目前有一个提案组(github.com/ljharb/proposal- promise-try)提供了 Promise.try 方法替代上面的写法。

```js
const f = () => console.log ('now'); 
Promise.try(f) ; 
console.log ('next'); 
// now 
// next 
```



## 12. 应用

### 12.1 异步加载图片

```js
function loadimageAsync(url) { 
	return new Promise(function(resolve, reject) { 
        var image= new Image();
		image.onload =function() { 
			resolve(image);
        }
		image.onerror = function() { 
			reject(new Error ('Could not load image at '+ url));
        }
		image.src = url; 
    })
}                      
```

### 12.2 实现AJAX操作

```js
var getJSON = function(url) { 
	var promise= new Promise(function(resolve , reject) { 
        var client= new XMLHttpRequest() ; 
        client.open ("GET", url); 
        client.onreadystatechange = handler ; 
        client.responseType = "json"; 
        client.setRequestHeader ("Accept", "applic ation/json"); 
        client.send();
    }

    function handler() { 
        if (this.readyState !== 4) { 
            return; 
        }
    	if (this.status === 200) { 
    		resolve(this.response) ; 
    	} else { 
    		reject(new Error(this.statusText)) ; 
        }
    }); 
	return promise;
}

getJSON ("/posts.json").then(function(json) { 
	console.log('Contents :'+ json);
}, function(error) { 
	console.error('出错了', error);
});
```

### 12.3 Generator 函数与 Promise 的结合

```js
function getFoo() {
    return new Promise(function (resolve, reject) {
        resolve('foo');
    });
}

var g = function* () {
    try {
        var foo = yield getFoo();
        console.log(foo);
    } catch (e) {
        console.log(e);
    }
};

function run(generator) {
    var it = generator();

    function go(result) {
        if (result.done) return result.value;
        return result.value.then(function (value) {
            return go(it.next(value));
        }, function (error) {
            return go(it.throw(error));
        })
    }
    go(it.next());
}
run(g);
// foo

上面的 Generator 函数 g 中有一个异步操作 getFoo ，它返回的就是一个 Promise 对象。函数 run 用来处理这个 Promise 对象，井调用下一个 next 方法 。
```

